-- Starter Email Templates (auto-generated by db/rebuild-templates.js)

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_corporate', 'Corporate - Initial Outreach', 'Lunch for the team at {{business_name}}?',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater breakfast and lunch for a lot of offices on the North Shore, everything from standing weekly orders to one-off team meetings.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} ever brings food in for the team, I''d like to put something together for you. Quick call or just hit reply, whichever is easier.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater breakfast and lunch for a lot of offices on the North Shore, everything from standing weekly orders to one-off team meetings.

If {{business_name}} ever brings food in for the team, I''d like to put something together for you. Quick call or just hit reply, whichever is easier.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'Corporate');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_medical', 'Medical - Initial Outreach', 'Catering for your {{city}} practice',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. A handful of practices in {{city}} have us drop off breakfast or lunch for their staff, morning coffee and bagels, sandwich trays for longer days, that sort of thing.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If catering is ever useful for {{business_name}}, I''d love to put together something that fits your schedule.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. A handful of practices in {{city}} have us drop off breakfast or lunch for their staff, morning coffee and bagels, sandwich trays for longer days, that sort of thing.

If catering is ever useful for {{business_name}}, I''d love to put together something that fits your schedule.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'Medical');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_school', 'School - Initial Outreach', 'Catering for {{business_name}} events',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater quite a few schools and PTOs in the area, teacher appreciation breakfasts, board meetings, staff lunches, end-of-year events.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} has anything coming up, happy to put together a menu that fits your group and your budget.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater quite a few schools and PTOs in the area, teacher appreciation breakfasts, board meetings, staff lunches, end-of-year events.

If {{business_name}} has anything coming up, happy to put together a menu that fits your group and your budget.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'School');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_worship', 'Worship - Initial Outreach', 'Catering for {{business_name}} gatherings',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for a few congregations and community groups in the area, fellowship gatherings, holiday meals, staff lunches, committee meetings.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} ever brings food in, I''d love to put something together. Simple menu, all local, and we deliver and set up.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for a few congregations and community groups in the area, fellowship gatherings, holiday meals, staff lunches, committee meetings.

If {{business_name}} ever brings food in, I''d love to put something together. Simple menu, all local, and we deliver and set up.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'Worship');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_general', 'General - Initial Outreach', 'Catering from Hometown near {{city}}',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for businesses, offices, schools, and events around {{city}}, breakfast trays, lunch spreads, one-time and recurring.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} ever needs food brought in, I''d like to be the first call. Quick call or reply here, whichever works.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for businesses, offices, schools, and events around {{city}}, breakfast trays, lunch spreads, one-time and recurring.

If {{business_name}} ever needs food brought in, I''d like to be the first call. Quick call or reply here, whichever works.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', NULL);

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_corporate_tasting', 'Corporate - Initial + Tasting', 'Lunch for the team at {{business_name}}?',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater breakfast and lunch for a lot of offices on the North Shore, everything from standing weekly orders to one-off team meetings.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} ever brings food in for the team, I''d like to put something together for you. Happy to swing by with a small tasting first, coffee, pastries, a sandwich or two, on me. Easiest way to see what we do.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater breakfast and lunch for a lot of offices on the North Shore, everything from standing weekly orders to one-off team meetings.

If {{business_name}} ever brings food in for the team, I''d like to put something together for you. Happy to swing by with a small tasting first, coffee, pastries, a sandwich or two, on me. Easiest way to see what we do.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'Corporate');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_medical_tasting', 'Medical - Initial + Tasting', 'Catering for your {{city}} practice',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. A handful of practices in {{city}} have us drop off breakfast or lunch for their staff, morning coffee and bagels, sandwich trays for longer days, that sort of thing.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If catering is ever useful for {{business_name}}, I''d love to put together something that fits your schedule. Happy to bring by a small tasting for the staff first, on me, so you can see what we do before committing.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. A handful of practices in {{city}} have us drop off breakfast or lunch for their staff, morning coffee and bagels, sandwich trays for longer days, that sort of thing.

If catering is ever useful for {{business_name}}, I''d love to put together something that fits your schedule. Happy to bring by a small tasting for the staff first, on me, so you can see what we do before committing.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'Medical');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_school_tasting', 'School - Initial + Tasting', 'Catering for {{business_name}} events',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater quite a few schools and PTOs in the area, teacher appreciation breakfasts, board meetings, staff lunches, end-of-year events.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} has anything coming up, happy to put together a menu that fits. I can also drop off a tasting tray for the staff room if it''d help, on me.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater quite a few schools and PTOs in the area, teacher appreciation breakfasts, board meetings, staff lunches, end-of-year events.

If {{business_name}} has anything coming up, happy to put together a menu that fits. I can also drop off a tasting tray for the staff room if it''d help, on me.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'School');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_worship_tasting', 'Worship - Initial + Tasting', 'Catering for {{business_name}} gatherings',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for a few congregations and community groups in the area, fellowship gatherings, holiday meals, staff lunches, committee meetings.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} ever brings food in, I''d love to put something together. Happy to drop by a tasting for your next gathering first, on me, so people can see what we do.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for a few congregations and community groups in the area, fellowship gatherings, holiday meals, staff lunches, committee meetings.

If {{business_name}} ever brings food in, I''d love to put something together. Happy to drop by a tasting for your next gathering first, on me, so people can see what we do.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', 'Worship');

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_initial_general_tasting', 'General - Initial + Tasting', 'Catering from Hometown near {{city}}',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for businesses, offices, schools, and events around {{city}}, breakfast trays, lunch spreads, one-time and recurring.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If {{business_name}} ever needs food brought in, I''d like to be the first call. Happy to swing by with a small tasting first, on me, so you can see what we do before committing.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Adam Rubin here, Hometown Coffee & Juice in {{nearest_location}}. We cater for businesses, offices, schools, and events around {{city}}, breakfast trays, lunch spreads, one-time and recurring.

If {{business_name}} ever needs food brought in, I''d like to be the first call. Happy to swing by with a small tasting first, on me, so you can see what we do before committing.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'initial', NULL);

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_followup1', 'Follow-up 1', 'Following up on catering',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Circling back on my note from last week about catering at {{business_name}}. I know inboxes get busy.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If catering isn''t on your radar right now, no problem, just let me know and I won''t keep reaching out. If it is, I can send over a menu or jump on a quick call.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Book a Call</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Circling back on my note from last week about catering at {{business_name}}. I know inboxes get busy.

If catering isn''t on your radar right now, no problem, just let me know and I won''t keep reaching out. If it is, I can send over a menu or jump on a quick call.

Book a call: {{booking_url}}
Order catering: {{catering_url}}
View menu: {{menu_url}}

Best,',
'follow_up_1', NULL);

INSERT INTO email_templates (id, name, subject, body_html, body_text, template_type, category) VALUES
('tpl_followup2', 'Final Follow-up', 'Just checking in on catering',
'<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Hi {{contact_name}},</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Last one from me, promise.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">If catering at {{business_name}} ever comes up, keep us in mind. We handle a lot of the offices, schools, and practices around {{city}}, and I''d love to be your spot when the time''s right.</p>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0 0 14px 0">Links below for whenever you need them.</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:28px 0;max-width:440px">
  <tr>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{catering_url}}" style="display:block;padding:10px 4px;background:#5a8fc4;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Order Catering</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{menu_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">View Menu</a>
    </td>
    <td width="33.33%" style="padding:0 3px">
      <a href="{{booking_url}}" style="display:block;padding:10px 4px;background:#ffffff;color:#5a8fc4;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;text-align:center;font-family:Arial,sans-serif;border:1px solid #5a8fc4;letter-spacing:0.2px">Chat With Me</a>
    </td>
  </tr>
</table>
<p style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;margin:0">Best,</p>',
'Hi {{contact_name}},

Last one from me, promise.

If catering at {{business_name}} ever comes up, keep us in mind. We handle a lot of the offices, schools, and practices around {{city}}, and I''d love to be your spot when the time''s right.

Links below for whenever you need them.

Order catering: {{catering_url}}
View menu: {{menu_url}}
Chat with me: {{booking_url}}

Best,',
'follow_up_2', NULL);

-- App settings (stored as key-value)
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

INSERT OR IGNORE INTO app_settings (key, value) VALUES
('from_email', ''),
('from_name', 'Adam Rubin at Hometown Coffee & Juice'),
('reply_to_email', ''),
('email_signature', '<div style="font-family:Arial,sans-serif;font-size:14px;color:#222;margin-top:36px">
  <div style="font-size:22px;color:#5a8fc4;font-weight:700;margin-bottom:2px;line-height:1.2">Adam Rubin</div>
  <div style="font-weight:700;color:#222;line-height:1.4">Hometown Coffee &amp; Juice</div>
  <div style="color:#555;line-height:1.4;margin-bottom:10px">Business Development Manager</div>
  <hr style="border:none;border-top:1px solid #d0d0d0;margin:10px 0;width:280px">
  <div style="line-height:1.8"><span style="color:#5a8fc4;font-weight:700;display:inline-block;width:72px">Mobile</span>847-224-5578</div>
  <div style="line-height:1.8"><span style="color:#5a8fc4;font-weight:700;display:inline-block;width:72px">Email</span><a href="mailto:adam@hometowncoffeejuice.com" style="color:#5a8fc4;text-decoration:none">adam@hometowncoffeejuice.com</a></div>
  <div style="line-height:1.8"><span style="color:#5a8fc4;font-weight:700;display:inline-block;width:72px">Website</span><a href="https://hometowncoffeejuice.com" style="color:#5a8fc4;text-decoration:none">hometowncoffeejuice.com</a></div>
  <div style="line-height:1.8"><span style="color:#5a8fc4;font-weight:700;display:inline-block;width:72px">Address</span>700 Vernon Ave., Glencoe IL</div>
</div>'),
('daily_send_limit', '80'),
('catering_url', 'https://www.toasttab.com/catering/locations/9e8dfec4-1c78-4969-8a56-a932e6035c08'),
('menu_url', 'https://static1.squarespace.com/static/5e83ff731e783a000bed08be/t/69d6b518e4daaf252f859ba4/1775678744575/Hometown+Catering+Menu+%28DIGITAL%29++2026+%281%29.pdf'),
('booking_url', 'https://calendar.google.com/calendar/appointments/schedules/AcZssZ1BFiYhd0UPEiCqYILN87pWEEqYPfM7bykLdjnjblojctuFDvCaF8eTsnGES2ObitYG4Z48Bp10'),
('resend_api_key', ''),
('business_address', '700 Vernon Ave., Glencoe IL'),
('location_glencoe', 'Glencoe'),
('location_winnetka', 'Winnetka'),
('location_glenview', 'Glenview'),
('location_lake_forest', 'Lake Forest');
